Models/Produit.cs
namespace gestion_commandes.Models
{
    public class Produit
    {
        public int Id { get; set; }

        public string Libelle { get; set; }

        public int QteStock { get; set; }

        public double Prix { get; set; }

        public int QteSeuil { get; set; }

        public string[]? Images { get; set; }

        public ICollection<Commande>? Commandes { get; set; }

        public ICollection<Panier>? Paniers { get; set; }


    }
}

Controllers/PanierController.cs
using gestion_commandes.Models;
using gestion_commandes.Services;
using gestion_commandes.Services.Impl;
using Microsoft.AspNetCore.Mvc;

namespace gestion_commandes.Controllers
{
    public class PanierController : Controller
    {
        private readonly ILogger<PanierController> _logger;
        private readonly IProduitService _produitService;
        private readonly IUtilisateurService _utilsateurService;
        private readonly IPanierService _panierService;
        private readonly IPanierProduitService _panierProduitService;

        public PanierController(ILogger<PanierController> logger, IProduitService produitService, IUtilisateurService utilsateurService, IPanierService panierService, IPanierProduitService panierProduitService) { 
            _logger = logger;
            _produitService = produitService;
            _utilsateurService = utilsateurService;
            _panierService = panierService;
            _panierProduitService = panierProduitService;
        }

        public async Task<IActionResult> AjoutForm(int produitId) {
            var produit = await _produitService.GetProduitByIdAsync(produitId);
            var panierProduit = new PanierProduit
            {
                Produit = produit,
            };
            if (TempData["userId"] != null)
            {
                TempData["userId"] =(int)TempData["userId"];
            }
            return View("Ajout", panierProduit);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToPanier([Bind("Quantite")] PanierProduit panierProduit)
        {
            if (ModelState.IsValid)
            {
                var client = _utilsateurService.GetUtilisateurById((int)TempData["userId"]);

                var panier =await  _panierService.GetPanierByIdClient(client.Id);
                panierProduit.Panier = panier;

                var panierProduitAdded = await _panierProduitService.Create(panierProduit);
                if(panierProduitAdded != null)
                {
                    return RedirectToAction(nameof(AjoutForm));
                }

            }
            return View("Ajout", panierProduit);

        }
    }


}

Controllers/ProduitController.cs
using gestion_commandes.Datas;
using gestion_commandes.Models;
using gestion_commandes.Services;
using Microsoft.AspNetCore.Mvc;

namespace gestion_commandes.Controllers;

public class ProduitController :Controller
{
    private readonly ILogger<ProduitController> _logger;

    private readonly IUtilisateurService _utilisateurService;
    private readonly IProduitService _produitService;
    private readonly IPanierService _panierService;
    private readonly IPanierProduitService _panierProduitService;
    private readonly ApplicationDbContext _context;

    public ProduitController(ILogger<ProduitController> logger, IUtilisateurService utilisateurService, IProduitService produitService, IPanierService panierService, IPanierProduitService panierProduitService, ApplicationDbContext context)
    {
        _logger = logger;
        _utilisateurService = utilisateurService;
        _produitService = produitService;
        _panierService = panierService;
        _panierProduitService = panierProduitService;
        _context = context;
    }

    public async Task<IActionResult> Index( int userId)
    {
        var produits = await _produitService.GetProduitListAsync();
        var user = await _utilisateurService.GetUtilisateurById(userId);
        TempData["userId"] = user.Id;
        var indexModel = new ProductIndexModel
        {
            User = user,
            Products = produits
        };
        return View(indexModel);
    }

    //public async Task<IActionResult> AddBasket(PanierProduit model)
    //{
    //    if (ModelState.IsValid) { 

    //    if(model.Quantite > 0)
    //    {
    //        var produit = await _produitService.GetProduitByIdAsync(model.ProduitId);
    //        var client = await _utilisateurService.GetUtilisateurById(model.Panier.ClientId);
    //        var panier = await _panierService.GetPanierByIdClient(4);

    //        var panierProduit = await _panierProduitService.GetProduitByPanierAndProdAsync(productId, panier.Id);

    //        if(panierProduit != null)
    //        {
    //            panierProduit.Quantite += quantite;

    //        }
    //        else
    //        {

    //            var basket = new PanierProduit
    //            {
    //                Produit = produit,
    //                Quantite = quantite,
    //                ProduitId = productId,
    //                Panier = panier,
    //                PanierId = panier.Id
    //            };

    //            _context.PanierProduits.Add(basket);
    //        }
    //        await _context.SaveChangesAsync();
    //    }
    //    TempData["message"] = "Produit ajoute avec succes !!";
    //    return RedirectToAction("Index", new {userId = clientId});
    //    }
    //}
}

Views/Produit/Index.cshtml
@using gestion_commandes.Models
@model ProductIndexModel
@{
}

<link href="/css/site.css" rel="stylesheet" />


<div class="container mx-auto py-8">
    <div class="" style="display:flex; flex-wrap: wrap; justify-content: space-around;">
        @foreach(var prod in Model.Products){
            <div class="bg-white shadow-md rounded-lg overflow-hidden" style="width: 250px; height: auto; paddind: 5px; margin:10px">
                <img src="/images/@(prod.Images[0])" alt="Product Image" style="width: 200px; height: 200px; border-radius: 10px;" class="w-full h-32 object-cover shadow-lg m-auto mt-2 mb-2">
                <div style="display: flex; justify-content:flex-end;">
                    <span style="width: 20px; height:20px; background-color: chartreuse; border-radius:100%; display:flex; justify-content:center; align-items:center">0</span>
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M3 3h2l.4 2M7 13h10l4-8H5.4m-.4 8a1 1 0 100 2h12a1 1 0 100-2H7zm-2 5a1 1 0 100-2 1 1 0 000 2zm14 0a1 1 0 100-2 1 1 0 000 2z" />
                    </svg>
                </div>
                <div class="p-4" style="width: 100%;">
                    <h2 class="text-sm text-gray-800" style="width: 100px; display:flex; justify-content:space-between">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="w-6 h-6">
                            <rect x="3" y="5" width="18" height="14" rx="2" />
                            <line x1="3" y1="8" x2="21" y2="8" stroke="currentColor" />
                            <text x="12" y="15" font-size="3" text-anchor="middle" fill="currentColor">Produit</text>
                        </svg>@prod.Libelle</h2>
                    <p class="text-gray-600 text-sm" style="width: 150px; display:flex; padding: 2px;" >
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="w-6 h-6">
                            <path d="M2 12l10-10h8v8l-10 10z" />
                            <circle cx="16" cy="8" r="1.5" />
                        </svg> @prod.Prix cfa
                    </p>
                    <div class="mt-4 space-x-2", style="display: column; width: 100%;">
                        <div class="mb-10" style="display: flex;justify-content:space-between; width: 100%; margin-bottom: 10px;">
                            <a href="@Url.Action("AjoutForm", "Panier", new {produitId = prod.Id})" value="@(prod.Id)" type="submit" class="ajouter-panier bg-blue-500 text-white px-2 py-1 text-xs rounded-md hover:bg-blue-600" style="font-size: 14px; width: 90px; display:flex; justify-content: space-around; background-color: rgb(101 163 13 / var(--tw-bg-opacity, 1));">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M3 3h2l.4 2M7 13h10l4-8H5.4m-.4 8a1 1 0 100 2h12a1 1 0 100-2H7zm-2 5a1 1 0 100-2 1 1 0 000 2zm14 0a1 1 0 100-2 1 1 0 000 2z" />
                                </svg>
                                Ajouter 
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>

    <!-- Pagination -->
    <div class="flex justify-center mt-8 space-x-2">
        <button class="px-4 py-2 bg-gray-300 rounded-md hover:bg-gray-400">Préc</button>
        <button class="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600">1</button>
        <button class="px-4 py-2 bg-gray-300 rounded-md hover:bg-gray-400">2</button>
        <button class="px-4 py-2 bg-gray-300 rounded-md hover:bg-gray-400">3</button>
        <button class="px-4 py-2 bg-gray-300 rounded-md hover:bg-gray-400">Suiv</button>
    </div>
</div>